### PR TITLE
Angus/scripting token support

### PR DESCRIPTION
**Pull request by veggiesaurus**
Basic scripting support:

- ~~User can generate a scripting API token and copy it to clipboard using the "Copy scripting token"~~
- Scripting tokens can be generated via the `/api/auth/refresh` endpoint (with `{"scripting": true}` in the JSON body)
- Scripting requests to `/api/scripting/*` are proxied to the backend after verifying that they have a valid auth token header (i.e. `Authoirzation: Bearer <token>`) and that the token has the validated claim `scripting: true`.
- A backend instance is started if no existing process is found (just like when proxying websocket upgrade requests from the frnotend).

### CODE REVIEW

**Comment by veggiesaurus** [comment]
moving back to draft until @confluence has finished her gRPC removal branch.

**Comment by veggiesaurus** [comment]
@confluence do you think this is ready for a PR and merge yet?

**Comment by confluence** [comment]
I'm still testing the controller integration, but it should be ready very soon.

**Comment by confluence** [comment]
This PR should be merged at the same time as the companion PRs in the [wrapper](https://github.com/idia-astro/carta-python/pull/31), [backend](https://github.com/CARTAvis/carta-backend/pull/1022), [frontend](https://github.com/CARTAvis/carta-frontend/pull/1785), [protocol buffers](https://github.com/CARTAvis/carta-protobuf/pull/65) and [website](https://github.com/CARTAvis/CARTAvis.github.io/pull/18).

**Review by confluence — APPROVED** [review]

**Pull request merged**
